server:
    port : 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@192.168.1.2:1521:orcl
    username: minh
    password: minhpro
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true